# site settings

title: Tianyuan Qiu
description: Tianyuan Qiu's Homepage
taglong: Computer Science B.E. Student @ SJTU
tagshort: Blog
url: https://frankq1024.github.io
baseurl: ""
permalink: pretty
repo: https://github.com/frankq1024/frankq1024.github.io

# author settings

author:
  name: Tianyuan Qiu
  email: frankq1024@gmail.com
photo: /attachments/images/photo.jpg

# social media links

social:
  linkedin: tianyuan-qiu
  github: frankq1024
  email: frankq1024@gmail.com

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
